# Generated by Django 5.2.6 on 2026-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_grade_alter_question_subject'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='specialized_subjects',
            field=models.ManyToManyField(blank=True, to='quiz.subject', verbose_name='Бейіндік пәндер'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='direction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бағыты (мысалы: Физ-мат)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(max_length=5, verbose_name='Сынып әрпі'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.IntegerField(verbose_name='Сынып саны'),
        ),
    ]
