# Generated by Django 5.2.6 on 2026-01-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.grade', verbose_name='Қай сыныпқа арналған?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject', verbose_name='Пән'),
        ),
    ]
