# Generated by Django 5.2.6 on 2026-01-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_grade_alter_question_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.testsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
