# Generated by Django 5.2.6 on 2026-01-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='score',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='testsession',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.question'),
        ),
    ]
